# Generated by Django 5.2.9 on 2026-02-14 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("theme_mode", models.CharField(blank=True, max_length=20)),
                (
                    "color_theme",
                    models.CharField(
                        choices=[
                            ("Red", "red"),
                            ("Pink", "pink"),
                            ("Fuchsia", "fuchsia"),
                            ("Purple", "purple"),
                            ("Violet", "violet"),
                            ("Indigo", "indigo"),
                            ("Blue", "blue"),
                            ("Azure", "azure"),
                            ("Cyan", "cyan"),
                            ("Jade", "jade"),
                            ("Green", "green"),
                            ("Lime", "lime"),
                            ("Yellow", "yellow"),
                            ("Amber", "amber"),
                            ("Pumpkin", "pumpkin"),
                            ("Orange", "orange"),
                            ("Sand", "sand"),
                            ("Gray", "gray"),
                            ("Zinc", "zinc"),
                            ("Slate", "slate"),
                        ],
                        default="pumpkin",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
