# Generated by Django 5.2.9 on 2026-02-14 15:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="color_theme",
            field=models.CharField(
                choices=[
                    ("Red", "red"),
                    ("Pink", "pink"),
                    ("Fuchsia", "fuchsia"),
                    ("Purple", "purple"),
                    ("Violet", "violet"),
                    ("Indigo", "indigo"),
                    ("Blue", "blue"),
                    ("Azure", ""),
                    ("Cyan", "cyan"),
                    ("Jade", "jade"),
                    ("Green", "green"),
                    ("Lime", "lime"),
                    ("Yellow", "yellow"),
                    ("Amber", "amber"),
                    ("Pumpkin", "pumpkin"),
                    ("Orange", "orange"),
                    ("Sand", "sand"),
                    ("Gray", "gray"),
                    ("Zinc", "zinc"),
                    ("Slate", "slate"),
                ],
                default="pumpkin",
                max_length=20,
            ),
        ),
    ]
