# Generated by Django 5.2.9 on 2026-02-15 03:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_userpreferences_theme_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="color_theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "Red"),
                    ("pink", "Pink"),
                    ("fuchsia", "Fuchsia"),
                    ("purple", "Purple"),
                    ("violet", "Violet"),
                    ("indigo", "Indigo"),
                    ("blue", "Blue"),
                    ("", "Azure"),
                    ("cyan", "Cyan"),
                    ("jade", "Jade"),
                    ("green", "Green"),
                    ("lime", "Lime"),
                    ("yellow", "Yellow"),
                    ("amber", "Amber"),
                    ("pumpkin", "Pumpkin"),
                    ("orange", "Orange"),
                    ("sand", "Sand"),
                    ("gray", "Gray"),
                    ("zinc", "Zinc"),
                    ("slate", "Slate"),
                ],
                default="pumpkin",
                max_length=20,
            ),
        ),
    ]
