# Generated by Django 5.2.9 on 2026-02-15 03:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_userpreferences_color_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="theme_mode",
            field=models.CharField(
                blank=True, choices=[("light", "Light"), ("dark", "Dark"), ("", "Auto")], default="", max_length=20
            ),
        ),
    ]
