# Generated by Django 5.2.9 on 2026-02-15 03:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_userpreferences_theme_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pictures/"),
        ),
    ]
