# Generated by Django 5.2.9 on 2026-02-28 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_purchase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase",
            options={"verbose_name": "Purchase", "verbose_name_plural": "Purchases"},
        ),
        migrations.AlterModelOptions(
            name="userpreferences",
            options={"verbose_name": "User Preference", "verbose_name_plural": "User Preferences"},
        ),
    ]
