# Generated by Django 5.2.9 on 2026-03-07 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_purchase_unique_user_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("profile_picture", models.ImageField(blank=True, null=True, upload_to="profile_pictures/")),
                ("receive_notifications", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
            },
        ),
        migrations.CreateModel(
            name="UserSitePreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "theme_mode",
                    models.CharField(
                        blank=True,
                        choices=[("light", "Light"), ("dark", "Dark"), ("", "System")],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "color_theme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("red", "Red"),
                            ("pink", "Pink"),
                            ("fuchsia", "Fuchsia"),
                            ("purple", "Purple"),
                            ("violet", "Violet"),
                            ("indigo", "Indigo"),
                            ("blue", "Blue"),
                            ("", "Azure"),
                            ("cyan", "Cyan"),
                            ("jade", "Jade"),
                            ("green", "Green"),
                            ("lime", "Lime"),
                            ("yellow", "Yellow"),
                            ("amber", "Amber"),
                            ("pumpkin", "Pumpkin"),
                            ("orange", "Orange"),
                            ("sand", "Sand"),
                            ("gray", "Gray"),
                            ("zinc", "Zinc"),
                            ("slate", "Slate"),
                        ],
                        default="pumpkin",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
            },
        ),
        migrations.DeleteModel(
            name="UserPreferences",
        ),
    ]
