# Generated by Django 5.2.9 on 2026-04-05 07:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_usersettings_usersitepreferences_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="state",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("REFUSED", "Refused")],
                default="ACCEPTED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
