# Generated by Django 5.2.9 on 2026-05-16 00:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0019_coursetag"),
        ("users", "0013_purchase_state_purchase_stripe_checkout_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersitepreferences",
            name="preferred_tags",
            field=models.ManyToManyField(blank=True, related_name="preferred_by_users", to="courses.coursetag"),
        ),
    ]
