# Generated by Django 5.2.9 on 2025-12-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SavingsAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("per_annum", models.FloatField()),
                (
                    "frequency",
                    models.IntegerField(choices=[(365, "DAILY"), (12, "MONTHLY"), (3, "QUARTERLY"), (1, "YEARLY")]),
                ),
            ],
        ),
    ]
