# Generated by Django 5.2.9 on 2025-12-09 10:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("savings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingsaccount",
            name="name",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
