graph LR
    A((Administrator))
    note["moștenește toate cazurile\nPublicatorului și Studentului"]
    A -..-> note

    A --> UC23["Gestionare utilizatori\nprin Django Admin"]
    A --> UC24["Gestionare cursuri ale\ntuturor publicatorilor"]
    A --> UC25["Utilizare sugestii automate\nde etichete"]
