# Generated by Django 5.2.9 on 2026-02-14 13:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_course_end_date_alter_course_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
