# Generated by Django 5.2.9 on 2026-02-15 05:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_module_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="order",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
