# Generated by Django 5.2.9 on 2026-02-15 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_module_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"permissions": [("publish_course", "Can publish course")]},
        ),
    ]
