# Generated by Django 5.2.9 on 2026-02-15 11:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_moduleprogression"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleprogression",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="progressions", to="courses.module"
            ),
        ),
    ]
