# Generated by Django 5.2.9 on 2026-02-28 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_alter_moduleprogression_module"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
    ]
