# Generated by Django 5.2.9 on 2026-02-28 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_question_answer_quizz_question_quiz"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Quizz",
            new_name="Quiz",
        ),
    ]
