# Generated by Django 5.2.9 on 2026-02-28 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_rename_quizz_quiz"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "Answer", "verbose_name_plural": "Answers"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order"], "verbose_name": "Module", "verbose_name_plural": "Modules"},
        ),
        migrations.AlterModelOptions(
            name="moduleprogression",
            options={"verbose_name": "Module Progression", "verbose_name_plural": "Module Progressions"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order"], "verbose_name": "Question", "verbose_name_plural": "Questions"},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "Quiz", "verbose_name_plural": "Quizzes"},
        ),
    ]
