# Generated by Django 5.2.9 on 2026-02-28 11:45

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_alter_answer_options_alter_course_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="module",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="quiz", to="courses.module"
            ),
        ),
    ]
