# Generated by Django 5.2.9 on 2026-03-07 06:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_alter_quiz_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="module",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
