# Generated by Django 5.2.9 on 2026-03-08 08:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models

import courses.utils


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0015_course_is_draft_module_is_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=courses.utils.resource_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "7z",
                                    "aac",
                                    "bmp",
                                    "csv",
                                    "doc",
                                    "docx",
                                    "flac",
                                    "gif",
                                    "ico",
                                    "jpeg",
                                    "jpg",
                                    "mp3",
                                    "mp4",
                                    "ods",
                                    "ogg",
                                    "ogv",
                                    "pdf",
                                    "png",
                                    "ppt",
                                    "pptx",
                                    "rar",
                                    "svg",
                                    "txt",
                                    "wav",
                                    "webm",
                                    "webp",
                                    "xls",
                                    "xlsx",
                                    "zip",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="resources", to="courses.module"
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
