# Generated by Django 5.2.9 on 2026-04-05 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    replaces = [
        ("courses", "0017_quiz_max_attempts_quizattempt"),
        ("courses", "0018_alter_quizattempt_completion_date"),
        ("courses", "0019_rename_score_quizattempt_grade"),
        ("courses", "0020_alter_quizattempt_grade"),
    ]

    dependencies = [
        ("courses", "0016_resources"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="max_attempts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("grade", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("completion_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="courses.quiz"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Attempt",
                "verbose_name_plural": "Quiz Attempts",
            },
        ),
    ]
