# Generated by Django 5.2.9 on 2026-04-05 07:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0017_quizattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="track_attempts",
            field=models.BooleanField(default=True),
        ),
    ]
