# Generated by Django 5.2.9 on 2026-05-16 00:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0018_quiz_track_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("courses", models.ManyToManyField(blank=True, related_name="tags", to="courses.course")),
            ],
            options={
                "verbose_name": "Course Tag",
                "verbose_name_plural": "Course Tags",
                "ordering": ["name"],
            },
        ),
    ]
