# Generated by Django 6.0.5 on 2026-05-31 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0019_coursetag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="course",
            name="start_date",
        ),
    ]
