# Generated by Django 6.0.5 on 2026-05-31 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0001_purchase"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="stripe_checkout_session_id",
            new_name="stripe_payment_id",
        ),
    ]
